---
title: "Evidencia 1: Análisis Inicial"
output: html_notebook
---

**Alumna:** Demmí Elizabeth Zepeda Rubio

**Matrícula:** A01709619

**Parte 1**

1.  **Investiga, ¿Cuál es la situación actual de COVID-19 a nivel mundial, en México, en tu estado de origen y en tu municipio, alcaldía o colonia?**

    De acuerdo con un artículo de la ONU (2024), en enero de 2024 se reporta un incremento ligero de contagiados por COVID-19, pero menciona que es debido a la estación de invierno. Hoy en día, el COVID-19 se considera otra enfermedad común que puede prevenirse con su vacuna respectiva y desde mayo del 2023, la ONU estableció que no es una emergencia de salud pública a nivel mundial, por lo que tanto en México, como en Jalisco y el resto del mundo, el COVID-19 se ha comenzado a tratar con más normalidad y menos pánico.

2.  **¿Cuál fue la primera variante del virus que se propagó a todo el mundo?**

    Un reporte de Yale (Katella, 2021), establece que la primera variante expuesta del COVID-19 es la variante Alfa, emergida en el 2020.

3.  **¿Cuáles son las otras variantes del virus que existen en otras regiones del mundo?**

Otras variantes conocidas y sus regiones, según Kathy Katella (2021) son:

-   Ómicron: variante encontrada en Botswana en Sudáfrica.

-   Delta: en India.

-   Beta: también en Sudáfrica.

4.  **¿Cómo buscarías información de la variante del virus en tu país?**

    Consultaría fuentes de información confiables como la Secretaría de Salud o el Gobierno de México.

5.  **Imagina que te encuentras en una situación similar a la de Li Wenliang, médico chino que intentó alertar sobre el brote de coronavirus en su país, pero fue detenido por las autoridades y obligado a retractarse, ¿qué harías en su caso? Selecciona un inciso:**

```         
-   **a) Lo reportas al centro de investigación o la universidad.**

-   **b) Lo reportas a la prensa.**

-   **c) Guardas la información.**

    **Elige y justifica tu respuesta.**

    Elegiría la respuesta a). Escogería un grupo de especialistas, reportaría que es cuestión de emergencia investigar dicho virus para que de manera inmediata se pueda establecer qué medidas de precaución tomar.
```

**Parte 2**

\`\`\`{# EVIDENCIA 1 - PARTE 2}

library('BiocManager') library('Biostrings')

# mostrar las rutas

rutaSARS_UNO \<- "D:\\demmi\\Documents\\R Codes\\Evidencia1\\sequenceSARS-CoV-2humanKAZS162023 surface glycoprotein (S) gene.fasta" rutaSARS_DOS \<- "D:\\demmi\\Documents\\R Codes\\Evidencia1\\sequenceSARS-CoV-2humanKAZS152023 surface glycoprotein (S) gene.fasta" rutaSARS_TRES \<- "D:\\demmi\\Documents\\R Codes\\Evidencia1\\sequenceSARS-CoV-2humanUSANY-CDC-QDX950284662024.fasta" rutaSARS_CUATRO \<- "D:\\demmi\\Documents\\R Codes\\Evidencia1\\sequenceSARS-CoV-2humanUSACA-CDC-QDX949667092024.fasta" rutaSARS_CINCO \<- "D:\\demmi\\Documents\\R Codes\\Evidencia1\\sequenceSARS-CoV-2humanUSANY-CDC-QDX948979042024.fasta"

# leer las secuencias desde los archivos fasta, y sus números de Accession

secuenciaSARS_UNO\<- readDNAStringSet(rutaSARS_UNO) #PP708947.1 secuenciaSARS_DOS \<- readDNAStringSet(rutaSARS_DOS) #PP709073.1 secuenciaSARS_TRES \<- readDNAStringSet(rutaSARS_TRES) #PP709071.1 secuenciaSARS_CUATRO \<- readDNAStringSet(rutaSARS_CUATRO) \# secuenciaSARS_CINCO \<- readDNAStringSet(rutaSARS_CINCO)

# una lista para después llamar a las secuencias en las funciones

secuencias \<- list(secuenciaSARS_UNO, secuenciaSARS_DOS, secuenciaSARS_TRES, secuenciaSARS_CUATRO, secuenciaSARS_CINCO)

# calcula la longitud de las secuencias de cada variante

{longitud_calc \<- function(secuencia, numero){ longitudes \<- sapply(seq_along(secuencia), function(i) { length \<- nchar(gsub("[\n-]", "", secuencia[i])) cat("Longitud de secuencia SARS", numero, ": ", length, "\n") return(length) }) return(longitudes) }

# para imprimirlo uniforme

for (i in 1:5) { longitud_calc(secuencias[[i]], i)} }

# Bases de ADN

# para la gráfica

nucleotidos_calc_graph \<- function(secuencia){ nucleotidos_graph \<- c("A", "C", "G", "T") freq_nucleotidos_graph \<- alphabetFrequency(secuencia, baseOnly = TRUE) names(freq_nucleotidos_graph) \<- nucleotidos_graph return(freq_nucleotidos_graph) }

variantes \<- c("SARS 1", "SARS 2", "SARS 3", "SARS 4", "SARS 5") bases \<- sapply(secuencias, nucleotidos_calc_graph)

{barplot( t(bases), beside = TRUE, legend.text = variantes, args.legend = list(x = "topright", bty = "n"), col = c("blue", "red", "green", "orange", "purple"), ylim = c(0, 10000), main = "Comparación de nucleótidos en variantes del virus SARS-CoV-2", xlab = "Nucleótidos", ylab = "Cantidad", yaxt = "n" #Evita que se dibujen las mediciones predeterminadas del eje y )}

axis(2, at = seq(0, 10000, by = 1000), labels = seq(0, 10000, by = 1000))

# ¿Cuál es el %GC de cada variante?

{nucleotidos_calc \<- function(secuencia, numero){ nucleotidos \<- c("A", "C", "G", "T") freq_nucleotidos \<- alphabetFrequency(secuencia, baseOnly = TRUE) names(freq_nucleotidos) \<- nucleotidos cat("En secuencia SARS ", numero, ":\n", sep = "") for (n in nucleotidos){ cat(n, ": ", freq_nucleotidos[[n]], "\n", sep = "") } cat("\n") }

# para imprimirlo y se vea uniforme

for (i in 1:5) { nucleotidos_calc(secuencias[[i]], i)} }

{porcentajeGC \<- function(secuencia, numero){ nucleotidos \<- c("A", "C", "G", "T") freq_nucleotidos \<- alphabetFrequency(secuencia, baseOnly = TRUE) names(freq_nucleotidos) \<- nucleotidos totalbases \<- sum(freq_nucleotidos) sumadeGC \<- sum(freq_nucleotidos[2],freq_nucleotidos[3]) porcentaje \<- (sumadeGC/totalbases)\*100 cat("En secuencia SARS ", numero, ":\n", sep = "") cat("C: ", freq_nucleotidos[2], "\nG: ", freq_nucleotidos[3], "\nPorcentaje de GC: ", porcentaje, "%\n") cat("\n") }

# para imprimirlo y se vea uniforme

for (i in 1:5) { nucleotidos_sec \<- porcentajeGC(secuencias[[i]], i)} }

# secuencias contrasentido

{contrasentido \<- function(secuencia, numero) { contrasentido_sec \<- reverseComplement(secuencia) cat("Secuencia contrasentido de SARS", numero, ":\n") print(contrasentido_sec) cat("\n") }

for (i in 1:5) { contrasentido(secuencias[[i]], i)} }

\`\`\`

Las gráficas que se integran en este código representan la comparación de las bases/nucleótidos que están presentes en las cinco variantes de SARS-Cov-2, no son sus porcentajes, son sus cantidades tal cual. En el eje y se muestran las cantidades, en el eje x los nombres de las bases, y las barras, según su color, representa a que variante pertenece.

Todas las variantes escogidas parecen tener una menor cantidad de C y G a comparación con A y T, sin embargo, la variante 1 y 2 tienen cantidades mucho menores de todas las bases comparadas con las variantes 3, 4 y 5.

**Referencias**

*Información Conjunta ante Alertas de Epidemias por Virus Respiratorios.* (2024, 10 de enero). Organización Panamericana de la Salud. <https://www.paho.org/es/noticias/10-1-2024-informacion-conjunta-ante-alertas-epidemias-por-virus-respiratorios>

Katella, K. (2021, 10 de diciembre). *Omicron, Delta, Alpha, and More: What To Know About the Coronavirus Variants.* Yale Medicine. <https://www.yalemedicine.org/news/covid-19-variants-of-concern-omicron>
